config/routes.rb
Rails.application.routes.draw do
  resources :patients
  root to: "patients#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/patient.rb
class Patient < ApplicationRecord
  enum gender: { Female: 0, Male: 1}
  validates_uniqueness_of :firstname, :scope => :lastname
  validates_presence_of :firstname
  validates_presence_of :lastname
  validates_length_of :phone, maximum: 10
  validates_length_of :phone, minimum: 10
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token


  # GET /patients
  def index
    if params[:search]
      search=params[:search]
      @patients = Patient.where("firstname LIKE ?", "%#{search}%")
    else
      @patients = Patient.all
    end
  end

  # GET /patients/1
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        flash[:success] = "Welcome to the Sample App!"
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_patient
      @patient = Patient.find(params[:id]) unless params["id"]=="search"
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:firstname, :lastname, :age, :dobb, :gender, :phone, :free_text)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PatientListApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark primary-color">
      <div id="navbarNavAltMarkup">
          <div class="navbar-nav">
              <a class="nav-item nav-link active" href=<%= patients_path %> >Home <span class="sr-only">(current)</span></a>
          </div>
      </div>
    </nav>
    <br>
    <div class="main">
      <%= yield %>
    <div>
    <footer class="footer page-footer font-small primary-color pt-4 mt-4">
      <div class="container-fluid text-center text-md-left">
          <div class="row">
             <div class="col-md-6">
                <h5 class="text-uppercase">Footer</h5>
              </div>
          </div>
      </div>
    </footer>
  </body>
</html>

app/views/patients/_form.html.erb
<div>
  <%= form_with(model: patient, local: true) do |form| %>
    <% if patient.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

        <ul>
        <% patient.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="container card-body card">

          <%= form.label :first_name, class: "ttitle" %><span class="color_me_fn" style="display: none">Required</span>
          <%= form.text_field :firstname, class: "first_name" %>
          <br>

          <%= form.label :last_name, class: "ttitle" %><span class="color_me_ln" style="display: none">Required</span>
          <%= form.text_field :lastname, class: "last_name" %>
          <br>

          <%= form.label :age, class: "ttitle" %><span class="age_css" style="display: none">Patient should be above 1 year</span>
          <%= form.number_field :age, class: "age" %>
          <br>

          <%= form.label :dob, class: "ttitle" %>
          <div class="container show_force">
            <span class="datetime"> <%= form.date_select :dobb, :start_year=>1900, :html=>{:class => "input-mini show_force"} %></span>
          </div>
          <br>

          <%= form.label :gender, class: "ttitle" %>
          <%= form.select :gender, %w{Male Female}, :prompt => 'Select', required: true, placeholder: 'Gender', class: 'form-control', id: 'show_force'
           %>
          <br>

          <%= form.label :phone, class: "ttitle" %><span class="color_me_nl" style="display: none">Length should be 10.</span>
          <%= form.text_field :phone, class: "number" %>
          <br>

          <%= form.label "Details", class: "ttitle" %>
          <%= form.text_area :free_text %>

      <div class="text-center mt-4">
        <%= form.submit "SUBMIT", class: "btn btn-success btn-block btn-rounded z-depth-1 submit_form", id: "submit_form" %>
      </div>
    </div>
  <% end %>
</div>
<script>
  $(document).ready(function(){
      $("#submit_form").click(function(){
        var falsee=0;

        var firstName = $('.first_name')[0].value
        if (firstName  == "") {
          $(".color_me_fn").css('background', 'red');
          $(".color_me_fn").show();
          falsee=1;
        }
        else{
          $(".color_me_fn").hide();
        }

        var lastName = $('.last_name')[0].value
        if (lastName  == "") {
          $(".color_me_ln").css('background', 'red');
          $(".color_me_ln").show();
          falsee=1;
        }
        else{
          $(".color_me_ln").hide();
        }

        var number = $('.number')[0].value
        if (number.length != 10) {
          $(".color_me_nl").css('background', 'red');
          $(".color_me_nl").show();
          falsee=1;
        }
        else{
          $(".color_me_nl").hide();
        }

        var age = $('.age')[0].value
        if (age < 1) {
          $(".age_css").css('background', 'red');
          $(".age_css").show();
          falsee=1;
        }
        else{
          $(".color_me_nl").hide();
        }

        if(falsee==1){
          return false;
        }
        return true;
      });
  });
</script>

app/views/patients/edit.html.erb
<p class="h4 text-center mb-4">Editing Patient</p>
<%= render 'form', patient: @patient %>
<%= link_to '<- Back', patients_path, class:"btn btn-default" %>
<%= link_to 'Show', @patient, class:"btn btn-brown" %>

app/views/patients/index.html.erb
<div>
  <%= form_tag(patients_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search By Name", class: "size_5_perc" %>
    <%= submit_tag "Search", :name => nil, class: "btn btn-success btn-rounded" %>
    <%= link_to 'Clear Search', patients_path, {class: 'btn btn-primary'} %>
  <% end %>
  <% if @patients.blank? %>
    <blockquote class="blockquote bq-danger">
      <h5 class="bq-title">There are no match</h5>
    </blockquote>
  <% end %>
  <%= react_component('PatientsShow', {Patients:@patients}) %>
</div>
<br>

<%= link_to 'For Adding New Patient Click Here', new_patient_path, {class: 'btn btn-primary'} %>
<p class="bottom-right" id="notice"><%= notice %></p>

app/views/patients/new.html.erb
<p class="h4 text-center mb-4">New Patients</p>
<%= render 'form', patient: @patient %>
<%= link_to '<- Back', patients_path, class:"btn btn-unique " %>

app/views/patients/show.html.erb
<p class="h4 text-center mb-4">Profile</p>
<div class="container card-body card">
  <p>
    <strong>Firstname:</strong>
    <%= @patient.firstname %>
  </p>

  <p>
    <strong>Lastname:</strong>
    <%= @patient.lastname %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= @patient.age %>
  </p>

  <p>
    <strong>Dob:</strong>
    <%= @patient.dobb %>
  </p>

  <p>
    <strong>Gender:</strong>
    <%= @patient.gender %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= @patient.phone %>
  </p>

  <p>
    <strong>Free text:</strong>
    <%= @patient.free_text %>
  </p>
</div>

<%= link_to '<- Back', patients_path, class:"btn btn-brown" %>
<%= link_to 'Edit', edit_patient_path(@patient), class:"btn btn-primary" %>
<p class="bottom-right" id="notice">helllo<%= notice %></p>